/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DAO.Apprenants;
import DAO.Connexion;
import DAO.Cours;
import DAO.Inscription;
import IMPDAO.IMP_Apprenants;
import IMPDAO.IMP_Cours;
import IMPDAO.IMP_FACTURE;
import IMPDAO.IMP_Frais_Cours;
import IMPDAO.IMP_Frais_inscription;
import IMPDAO.IMP_Inscription;
import IMPDAO.IMP_JTABLE;
import IMPDAO.IMP_USERS;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.parser.PdfTextExtractor;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Meeriame
 */
public class Principal_user extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal_user() {
        initComponents();
        // this.setLocationRelativeTo(null);
        new IMP_Frais_inscription().charge_combo_typeInscription(cbo_type_inscrip);
        new IMP_Cours().charge_combo_cours(cbo_cours);
        new IMP_Apprenants().liste_des_apprenants(jTable_Apprenant);
        new IMP_Inscription().liste_des_inscrits_et_reinscrits(jTable_Inscription);
        new IMP_Apprenants().charge_combo_matricule(cbo_matricule);
        tb_matricule.setEnabled(true);
//        tb_netApayer.setText("");

    }
    String path = "src/images/photo.png";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        tb_nom = new javax.swing.JTextField();
        tb_tel = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        tb_prenom = new javax.swing.JTextField();
        cbo_genre = new javax.swing.JComboBox<>();
        jLabel83 = new javax.swing.JLabel();
        tb_recherche_app = new javax.swing.JTextField();
        btn_recherche = new javax.swing.JButton();
        jLabel84 = new javax.swing.JLabel();
        btn_ajouter = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_imprimer = new javax.swing.JButton();
        jLabel85 = new javax.swing.JLabel();
        tb_matricule = new javax.swing.JTextField();
        lab_photoo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_annuler = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Apprenant = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        tb_netApayer = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        cbo_cours = new javax.swing.JComboBox<>();
        jLabel76 = new javax.swing.JLabel();
        tb_recher_inscrip = new javax.swing.JTextField();
        jButton34 = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        btn_ajout_inscrip = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        tb_frais_inscrip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbo_type_inscrip = new javax.swing.JComboBox<>();
        jLabel81 = new javax.swing.JLabel();
        tb_montant = new javax.swing.JTextField();
        btn_annul_cours2 = new javax.swing.JButton();
        cbo_matricule = new javax.swing.JComboBox<>();
        tb_montant_payer = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        tb_reste_a_payer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Inscription = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DES APPRENANTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 0, 466, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LISTE DES APPRENANTS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 340, 30));

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel79.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel79.setText("Matricule :");
        jPanel27.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        jLabel80.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel80.setText("Nom :");
        jPanel27.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 30));

        tb_nom.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel27.add(tb_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 270, 30));

        tb_tel.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel27.add(tb_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 270, 30));

        jLabel82.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel82.setText("Prenom");
        jPanel27.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        tb_prenom.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel27.add(tb_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 270, 30));

        cbo_genre.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        cbo_genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner", "Masculin", "Feminin" }));
        jPanel27.add(cbo_genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 262, 28));

        jLabel83.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel83.setText("Genre :");
        jPanel27.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 90, 20));

        tb_recherche_app.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_recherche_app.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tb_recherche_app.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_recherche_appKeyPressed(evt);
            }
        });
        jPanel27.add(tb_recherche_app, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 260, 30));

        btn_recherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_26px.png"))); // NOI18N
        btn_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechercheActionPerformed(evt);
            }
        });
        jPanel27.add(btn_recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 40, 30));

        jLabel84.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel84.setText("Rechercher");
        jPanel27.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 100, 20));

        btn_ajouter.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        btn_ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_16.png"))); // NOI18N
        btn_ajouter.setText("AJOUTER");
        btn_ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ajouterMouseClicked(evt);
            }
        });
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });
        jPanel27.add(btn_ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 150, 50));

        btn_modifier.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        btn_modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_26px.png"))); // NOI18N
        btn_modifier.setText("MODIFIER");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });
        jPanel27.add(btn_modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 150, 50));

        btn_imprimer.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        btn_imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_print_32.png"))); // NOI18N
        btn_imprimer.setText("IMPRIMER");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });
        jPanel27.add(btn_imprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 160, 50));

        jLabel85.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel85.setText("Telephone");
        jPanel27.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 110, 30));

        tb_matricule.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_matricule.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel27.add(tb_matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 270, 30));

        lab_photoo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_photoo.setText("PHOTO");
        lab_photoo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel27.add(lab_photoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 150, 120));

        jButton1.setText("PARCOURIR .....");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        btn_annuler.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        btn_annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_16px.png"))); // NOI18N
        btn_annuler.setText("ANNULER");
        btn_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annulerActionPerformed(evt);
            }
        });
        jPanel27.add(btn_annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 150, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("*");
        jPanel27.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, 20, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("*");
        jPanel27.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 20, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("*");
        jPanel27.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 20, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("*");
        jPanel27.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 20, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("*");
        jPanel27.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, 20, -1));

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1040, 310));

        jTable_Apprenant.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jTable_Apprenant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Matricules", "Noms", "Prenoms", "Genre", "Telephone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Apprenant.setGridColor(new java.awt.Color(204, 204, 204));
        jTable_Apprenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ApprenantMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Apprenant);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1040, 200));

        jTabbedPane1.addTab("APPRENANTS", jPanel1);

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(0, 102, 102));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GESTION DES INSCRIPTIONS");
        jPanel15.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 0, 466, 70));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jLabel8.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LISTE DES INSCRIPTIONS");
        jPanel14.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 340, 30));

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel73.setText("Matricule Eleve :");
        jPanel26.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 30));

        jLabel74.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("Frais Inscription");
        jPanel26.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 170, 30));

        tb_netApayer.setEditable(false);
        tb_netApayer.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_netApayer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tb_netApayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_netApayerActionPerformed(evt);
            }
        });
        jPanel26.add(tb_netApayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 170, 30));

        jLabel75.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel75.setText("Cours :");
        jPanel26.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 30));

        cbo_cours.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        cbo_cours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_coursActionPerformed(evt);
            }
        });
        jPanel26.add(cbo_cours, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, 28));

        jLabel76.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel76.setText("Type d'inscription :");
        jPanel26.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 20));

        tb_recher_inscrip.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_recher_inscrip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel26.add(tb_recher_inscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 260, 30));

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_26px.png"))); // NOI18N
        jPanel26.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 40, 30));

        jLabel77.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel77.setText("Rechercher");
        jPanel26.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 100, 20));

        btn_ajout_inscrip.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        btn_ajout_inscrip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_16.png"))); // NOI18N
        btn_ajout_inscrip.setText("VALIDER");
        btn_ajout_inscrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ajout_inscripMouseClicked(evt);
            }
        });
        btn_ajout_inscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajout_inscripActionPerformed(evt);
            }
        });
        jPanel26.add(btn_ajout_inscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 50));

        jButton9.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_26px.png"))); // NOI18N
        jButton9.setText("MODIFIER");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 150, 50));

        jButton10.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_print_32.png"))); // NOI18N
        jButton10.setText("IMPRIMER");
        jPanel26.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 160, 50));

        jLabel78.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel78.setText("Net à Payer :");
        jPanel26.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 110, 30));

        tb_frais_inscrip.setEditable(false);
        tb_frais_inscrip.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_frais_inscrip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel26.add(tb_frais_inscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 170, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setText("GNF");
        jPanel26.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 60, 30));

        cbo_type_inscrip.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        cbo_type_inscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_type_inscripActionPerformed(evt);
            }
        });
        jPanel26.add(cbo_type_inscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 230, 28));

        jLabel81.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel81.setText("Frais Cours :");
        jPanel26.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 110, 30));

        tb_montant.setEditable(false);
        tb_montant.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_montant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tb_montant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_montantActionPerformed(evt);
            }
        });
        jPanel26.add(tb_montant, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 170, 30));

        btn_annul_cours2.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        btn_annul_cours2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_16px.png"))); // NOI18N
        btn_annul_cours2.setText("ANNULER");
        btn_annul_cours2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annul_cours2ActionPerformed(evt);
            }
        });
        jPanel26.add(btn_annul_cours2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 150, 50));

        cbo_matricule.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        cbo_matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_matriculeActionPerformed(evt);
            }
        });
        jPanel26.add(cbo_matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 230, 28));

        tb_montant_payer.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_montant_payer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tb_montant_payer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_montant_payerMouseExited(evt);
            }
        });
        tb_montant_payer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_montant_payerActionPerformed(evt);
            }
        });
        tb_montant_payer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_montant_payerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tb_montant_payerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tb_montant_payerKeyTyped(evt);
            }
        });
        jPanel26.add(tb_montant_payer, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 170, 30));

        jLabel87.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel87.setText("Montant payer :");
        jPanel26.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 130, 30));

        jLabel88.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 153, 0));
        jLabel88.setText("Reste à Payer :");
        jPanel26.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 130, 30));

        tb_reste_a_payer.setEditable(false);
        tb_reste_a_payer.setBackground(new java.awt.Color(204, 0, 0));
        tb_reste_a_payer.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        tb_reste_a_payer.setForeground(new java.awt.Color(255, 255, 255));
        tb_reste_a_payer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tb_reste_a_payer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_reste_a_payerActionPerformed(evt);
            }
        });
        jPanel26.add(tb_reste_a_payer, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 170, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setText("GNF");
        jPanel26.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 60, 30));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel9.setText("GNF");
        jPanel26.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 60, 30));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel10.setText("GNF");
        jPanel26.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 60, 30));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel11.setText("GNF");
        jPanel26.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 60, 30));

        jButton2.setText("IMPRIMER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("*");
        jPanel26.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, 20, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("*");
        jPanel26.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 20, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("*");
        jPanel26.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 20, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("*");
        jPanel26.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 20, -1));

        jPanel14.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1040, 310));

        jTable_Inscription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Matricule", "Nom", "Prenom", "Telephone", "Type", "Cours", "Montant Payer", "Montant Restant", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Inscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_InscriptionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Inscription);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 407, 1040, 190));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("INSCRIPTION", jPanel8);

        jMenuBar1.setForeground(new java.awt.Color(153, 0, 0));
        jMenuBar1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_list_48px.png"))); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(153, 0, 0));
        jMenuItem1.setText("DECONNEXION");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajout_inscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajout_inscripActionPerformed
        int verif = new IMP_Inscription().Verification_apprenant_inscrit(cbo_matricule.getSelectedItem().toString(), cbo_cours.getSelectedItem().toString());
        if (cbo_type_inscrip.getSelectedItem().toString().equalsIgnoreCase("Selectionner")) {
            JOptionPane.showMessageDialog(null, "Le Type est Obligatoire");
        } else if (cbo_matricule.getSelectedItem().toString().equalsIgnoreCase("Selectionner")) {
            JOptionPane.showMessageDialog(null, "Le Matricule est Obligatoire");
        } else if (cbo_cours.getSelectedItem().toString().equalsIgnoreCase("Selectionner")) {
            JOptionPane.showMessageDialog(null, "Le Cours est Obligatoire");
        }else if(tb_montant_payer.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Le montant payer est obligatoire");
            tb_montant_payer.requestFocus();
        }
        else if (verif != 0) {
            JOptionPane.showMessageDialog(null, "Cet apprenant est deja inscrit en cours de " + new IMP_Cours().Get_nom_cours_selon_id(verif));
        } else {
            int id_facture = new IMP_FACTURE().Enregistrer_facture(Integer.parseInt(tb_netApayer.getText()), Integer.parseInt(tb_montant_payer.getText()), Integer.parseInt(tb_reste_a_payer.getText()));
            boolean enreg = new IMP_Inscription().InscriptionApprenant(cbo_matricule.getSelectedItem().toString(), cbo_cours.getSelectedItem().toString(), cbo_cours.getSelectedItem().toString(), cbo_type_inscrip.getSelectedItem().toString(), cbo_type_inscrip.getSelectedItem().toString(), id_facture);
            if (enreg) {
                if (cbo_type_inscrip.getSelectedItem().toString().equalsIgnoreCase("INSCRIPTION")) {
                    JOptionPane.showMessageDialog(null, "Inscription faite avec succès");
                    vider_champs_inscription();
                    new IMP_Inscription().liste_des_inscrits_et_reinscrits(jTable_Inscription);
                } else {
                    JOptionPane.showMessageDialog(null, "Réinscription faite avec succès");
                    vider_champs_inscription();
                    new IMP_Inscription().liste_des_inscrits_et_reinscrits(jTable_Inscription);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Inscription Echouée");
            }

        }


    }//GEN-LAST:event_btn_ajout_inscripActionPerformed

    private void btn_ajout_inscripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajout_inscripMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ajout_inscripMouseClicked

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        if (tb_matricule.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Le matricule est Obligatoire ");
            tb_matricule.requestFocus();
        } else if (tb_nom.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Le Nom est Obligatoire ");
            tb_nom.requestFocus();
        } else if (tb_prenom.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Le Prenom est Obligatoire ");
            tb_prenom.requestFocus();
        } else if (cbo_genre.getSelectedItem().toString().equalsIgnoreCase("Selectionner")) {
            JOptionPane.showMessageDialog(null, "Le Genre est Obligatoire ");
            cbo_genre.requestFocus();
        } else if (tb_tel.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Le Telephone est Obligatoire ");
            tb_tel.requestFocus();
        } else {
            Apprenants appren = new Apprenants();
            appren.setMatricule(tb_matricule.getText());
            appren.setNom(tb_nom.getText());
            appren.setPrenom(tb_prenom.getText());
            appren.setGenre(cbo_genre.getSelectedItem().toString());
            appren.setTel(tb_tel.getText());
            appren.setChemin_photo(path);

            int enreg = new IMP_Apprenants().Insertion_Apprenants(appren);
            if (enreg != 1062) {
                if (enreg != 0) {
                    JOptionPane.showMessageDialog(null, "Enregistrement effectuer avec succès");

                    new IMP_Apprenants().charge_combo_matricule(cbo_matricule);
                    vider_champs_apprenant();
                    new IMP_Apprenants().liste_des_apprenants(jTable_Apprenant);
                } else {
                    JOptionPane.showMessageDialog(null, "Enregistrement echouer");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Cet apprenant existe deja ");
            }

        }


    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajouterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ajouterMouseClicked

    private void cbo_type_inscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_type_inscripActionPerformed
        try {
            tb_frais_inscrip.setText(new IMP_Frais_inscription().get_montant_inscrip(cbo_type_inscrip.getSelectedItem().toString()));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbo_type_inscripActionPerformed

    private void cbo_coursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_coursActionPerformed
        try {
            tb_montant.setText(new IMP_Frais_Cours().Get_montant_cours_selon_nom_cours(cbo_cours.getSelectedItem().toString()));
            tb_netApayer.setText(new IMP_Inscription().Net_a_payer(cbo_type_inscrip.getSelectedItem().toString(), cbo_cours.getSelectedItem().toString()) + "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de get_montant" + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_cbo_coursActionPerformed

    private void tb_netApayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_netApayerActionPerformed

    }//GEN-LAST:event_tb_netApayerActionPerformed

    private void tb_montantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_montantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_montantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // PARCOURIR ET CHOISIR UNE IMAGE
        JFileChooser chose = new JFileChooser();
        chose.setDialogTitle("SELECTIONNER UNE IMAGE");
        chose.setFileFilter(new FileNameExtensionFilter("jpeg", "png", "jpg"));
        if (chose.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            path = chose.getSelectedFile().getAbsolutePath();
            ImageIcon con = new ImageIcon(path);
            Image img = con.getImage().getScaledInstance(lab_photoo.getWidth(), lab_photoo.getHeight(), Image.SCALE_SMOOTH);
            lab_photoo.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        int vid = JOptionPane.showConfirmDialog(null, "Voulez-vous Modifier ce Apprenant ?", "MODIFICATION APPRENANT", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (vid == JOptionPane.YES_OPTION) {
            if (tb_recherche_app.getText().equalsIgnoreCase("") || (!tb_recherche_app.getText().equalsIgnoreCase(tb_matricule.getText()))) {
                JOptionPane.showMessageDialog(null, "Le matricule à modifier svp");
            } else {
                Apprenants appren = new Apprenants();
                appren.setMatricule(tb_matricule.getText());
                appren.setNom(tb_nom.getText());
                appren.setPrenom(tb_prenom.getText());
                appren.setGenre(cbo_genre.getSelectedItem().toString());
                appren.setTel(tb_tel.getText());
                appren.setChemin_photo(path);

                int modif = new IMP_Apprenants().Modifier_apprenant(appren, tb_recherche_app.getText(), true);
                if (modif != 0) {
                    JOptionPane.showMessageDialog(null, "Modification effectuée avec succès");
                    vider_champs_apprenant();
                    new IMP_Apprenants().liste_des_apprenants(jTable_Apprenant);
                } else {
                    JOptionPane.showMessageDialog(null, "Modification echouée");
                }
            }
        }

    }//GEN-LAST:event_btn_modifierActionPerformed
    // ====================VIDAGE DES CHAMPS
    public void vider_champs_apprenant() {
        tb_matricule.setEnabled(true);
        tb_matricule.setText("");
        tb_nom.setText("");
        tb_prenom.setText("");
        cbo_genre.setSelectedItem("Selectionner");
        tb_tel.setText("");
        tb_recherche_app.setText("");
        lab_photoo.setIcon(null);

    }

  

    public void vider_champs_inscription() {
        tb_frais_inscrip.setText("");
        cbo_type_inscrip.setSelectedItem("Selectionner");
        cbo_cours.setSelectedItem("Selectionner");
        cbo_matricule.setSelectedItem("Selectionner");
        tb_montant.setText("");
        tb_netApayer.setText("");
        tb_recher_inscrip.setText("");
        tb_montant_payer.setText("");
        tb_reste_a_payer.getText();
    }
    private void jTable_ApprenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ApprenantMouseClicked
        if (evt.getClickCount() == 2) {

          tb_matricule.setEnabled(false);
            int i = jTable_Apprenant.getSelectedRow();
            tb_matricule.setText(jTable_Apprenant.getValueAt(i, 1).toString());
            tb_nom.setText(jTable_Apprenant.getValueAt(i, 2).toString());
            tb_prenom.setText(jTable_Apprenant.getValueAt(i, 3).toString());
            cbo_genre.setSelectedItem(jTable_Apprenant.getValueAt(i, 4).toString());
            tb_tel.setText(jTable_Apprenant.getValueAt(i, 5).toString());
            tb_recherche_app.setText(jTable_Apprenant.getValueAt(i, 5).toString());

      
      }    
            
            
//            tb_matricule.setEnabled(false);
//            int i = jTable_Apprenant.getSelectedRow();
//            tb_matricule.setText(jTable_Apprenant.getValueAt(i, 1).toString());
//            tb_nom.setText(jTable_Apprenant.getValueAt(i, 2).toString());
//            tb_prenom.setText(jTable_Apprenant.getValueAt(i, 3).toString());
//            cbo_genre.setSelectedItem(jTable_Apprenant.getValueAt(i, 4).toString());
//            tb_tel.setText(jTable_Apprenant.getValueAt(i, 5).toString());
//            tb_recherche_app.setText(jTable_Apprenant.getValueAt(i, 1).toString());
//            Apprenants app=new Apprenants();
//             ImageIcon con=new ImageIcon(app.getPhoto());
//             Image img=con.getImage().getScaledInstance(lab_photoo.getWidth(),lab_photoo.getHeight(), Image.SCALE_SMOOTH);
//             lab_photoo.setIcon(new ImageIcon(img));
//        }
    }//GEN-LAST:event_jTable_ApprenantMouseClicked

    private void btn_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annulerActionPerformed
        int vid = JOptionPane.showConfirmDialog(null, "Voulez-vous vider tout les champs ?", "VIDER LES CHAMPS", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (vid == JOptionPane.YES_OPTION) {
            vider_champs_apprenant();
            new IMP_Apprenants().liste_des_apprenants(jTable_Apprenant);
        }

    }//GEN-LAST:event_btn_annulerActionPerformed

    private void btn_annul_cours2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annul_cours2ActionPerformed
        int vide = JOptionPane.showConfirmDialog(null, "Voulez-vous vider tout les champs ?", "VIDER LES CHAMPS", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (vide == JOptionPane.YES_OPTION) {
            vider_champs_inscription();
        }
    }//GEN-LAST:event_btn_annul_cours2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int vid = JOptionPane.showConfirmDialog(null, "Voulez-vous vous deconnecté ?", "DECONNECTION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (vid == JOptionPane.YES_OPTION) {
            this.dispose();
            Login log = new Login();
            log.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cbo_matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_matriculeActionPerformed

    private void btn_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rechercheActionPerformed
 Apprenants app=new IMP_Apprenants().get_information_apprenant_selon_telephone(tb_recherche_app.getText());
      if(app!=null){
         if(app.getPhoto()!=null){
             ImageIcon con=new ImageIcon(app.getPhoto());
             Image img=con.getImage().getScaledInstance(lab_photoo.getWidth(),lab_photoo.getHeight(), Image.SCALE_SMOOTH);
             lab_photoo.setIcon(new ImageIcon(img)); 
         }
      tb_matricule.setText(app.getMatricule());
      tb_nom.setText(app.getNom());
      tb_prenom.setText(app.getPrenom());
      cbo_genre.setSelectedItem(app.getGenre());
      tb_tel.setText(app.getTel());
      }        






        // RECHERCHER EN TRIANT LE TABLEAU

//        if (tb_recherche_app.getText().equalsIgnoreCase("")) {
//            JOptionPane.showMessageDialog(null, "Entrer le Tel de L'apprenant");
//        } else {
  //         if (!new IMP_Apprenants().Recherche_apprenant(jTable_Apprenant, tb_recherche_app.getText())) {
//                JOptionPane.showMessageDialog(null, "L'Apprenant n'existe pas dans la base de donnée");
//            }
//        }
    }//GEN-LAST:event_btn_rechercheActionPerformed

    private void tb_recherche_appKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_recherche_appKeyPressed

    }//GEN-LAST:event_tb_recherche_appKeyPressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Inscription inscri = new Inscription();
        inscri.setMatricule(cbo_matricule.getSelectedItem().toString());
        inscri.setNom_cours(cbo_cours.getSelectedItem().toString());
        inscri.setType_inscrip(cbo_type_inscrip.getSelectedItem().toString());

        int modif = new IMP_Inscription().ModificationApprenant(cbo_matricule.getSelectedItem().toString(), cbo_cours.getSelectedItem().toString(), tb_montant.getText(), tb_frais_inscrip.getText(), cbo_type_inscrip.getSelectedItem().toString());
        if (modif != 1062) {
            JOptionPane.showMessageDialog(null, "Modification effectuée avec succès");
            vider_champs_inscription();
            new IMP_Inscription().liste_des_inscrits_et_reinscrits(jTable_Inscription);
        } else {
            JOptionPane.showMessageDialog(null, "Modification echouée");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable_InscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_InscriptionMouseClicked
        if (evt.getClickCount() == 2) {
            int i = jTable_Inscription.getSelectedRow();
            cbo_cours.setSelectedItem(jTable_Inscription.getValueAt(i, 6).toString());
            cbo_matricule.setSelectedItem(jTable_Inscription.getValueAt(i, 1).toString());
            cbo_type_inscrip.setSelectedItem(jTable_Inscription.getValueAt(i, 5).toString());
            tb_montant_payer.setText(jTable_Inscription.getValueAt(i,7).toString());
            tb_reste_a_payer.setText(jTable_Inscription.getValueAt(i,8).toString());
        }
    }//GEN-LAST:event_jTable_InscriptionMouseClicked

    private void tb_montant_payerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_montant_payerActionPerformed

    }//GEN-LAST:event_tb_montant_payerActionPerformed

    private void tb_montant_payerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_montant_payerKeyPressed
        try {
            // int netApayer = Integer.parseInt(tb_netApayer.getText());
//            int k=Integer.parseInt(tb_frais_inscrip.getText());
            int t = Integer.parseInt(tb_netApayer.getText());

            int montantPayer = Integer.parseInt(tb_montant_payer.getText());
            int resteAPayer = ((t) - montantPayer);
            tb_reste_a_payer.setText(resteAPayer + "");
            // tb_reste_a_payer.setText(String.valueOf(resteAPayer));
        } catch (Exception e) {
//    JOptionPane.showMessageDialog(null, "Erreur : " + e);
        }
    }//GEN-LAST:event_tb_montant_payerKeyPressed

    private void tb_reste_a_payerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_reste_a_payerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_reste_a_payerActionPerformed

    private void tb_montant_payerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_montant_payerMouseExited

    }//GEN-LAST:event_tb_montant_payerMouseExited

    private void tb_montant_payerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_montant_payerKeyTyped
        try {
            // int netApayer = Integer.parseInt(tb_netApayer.getText());
//            int k=Integer.parseInt(tb_frais_inscrip.getText());
            int t = Integer.parseInt(tb_netApayer.getText());

            int montantPayer = Integer.parseInt(tb_montant_payer.getText());
            int resteAPayer = ((t) - montantPayer);
            tb_reste_a_payer.setText(resteAPayer + "");
            // tb_reste_a_payer.setText(String.valueOf(resteAPayer));
        } catch (Exception e) {
//    JOptionPane.showMessageDialog(null, "Erreur : " + e);
        }
    }//GEN-LAST:event_tb_montant_payerKeyTyped

    private void tb_montant_payerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_montant_payerKeyReleased
        try {
            // int netApayer = Integer.parseInt(tb_netApayer.getText());
//            int k=Integer.parseInt(tb_frais_inscrip.getText());
            int t = Integer.parseInt(tb_netApayer.getText());

            int montantPayer = Integer.parseInt(tb_montant_payer.getText());
            int resteAPayer = ((t) - montantPayer);
            tb_reste_a_payer.setText(resteAPayer + "");
            // tb_reste_a_payer.setText(String.valueOf(resteAPayer));
        } catch (Exception e) {
//    JOptionPane.showMessageDialog(null, "Erreur : " + e);
        }
    }//GEN-LAST:event_tb_montant_payerKeyReleased
    //===============OUVRIR UN FICHIER PDF =================================
    public void monguide() {

        File fichier = new File("src/Etats/GUIDE_GESTION_CAFFAB.pdf");
// On vérifie que la classe Desktop soit bien supportée : 
        if (Desktop.isDesktopSupported()) {
            // On récupère l'instance du desktop : 
            Desktop desktop = Desktop.getDesktop();
            // On vérifie que la fonction open est bien supportée : 
            if (desktop.isSupported(Desktop.Action.OPEN)) {
                // Et on lance l'application associé au fichier pour l'ouvrir : 
                try {
                    desktop.open(fichier);
                } catch (Exception e) {
                }
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            InputStream fichier, logo;
            int id_inscrip = new IMP_Inscription().get_id_inscrip_selon_matri_et_cours(cbo_matricule.getSelectedItem().toString(), cbo_cours.getSelectedItem().toString());
//            int montant_total = new ImpTranche().get_montantTotal_tranche(CboNiveau.getSelectedItem().toString());

            //----Pour recuperer les objet en parametre
            Map<String, Object> parametre = new HashMap<>();
            ///---Prend le chemin de l'image
            logo = new FileInputStream("src/images/logo.png");
            parametre.put("para_logo", logo);
            String code_qr = "Matricule " + cbo_matricule.getSelectedItem() + "\nNom " + tb_nom.getText() + "\nPrénom " + tb_prenom.getText() + "\nGenre "
                    + cbo_genre.getSelectedItem().toString();
            parametre.put("para_codeQr", code_qr);
            parametre.put("para_id_inscrip", id_inscrip);
            ///////----Prend le chemin de l'etat à imprimer
            fichier = new FileInputStream("src/Etats/Etat_Facture.jasper");
            JasperPrint pr = JasperFillManager.fillReport(fichier, parametre, new Connexion().getConnection());
            JasperViewer.viewReport(pr, true);
//            parametre.put("para_montant_scolaire", montant_total);

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, " erreur impression2 " + ex.getLocalizedMessage());
        } catch (JRException ex) {
            Logger.getLogger(Principal_user.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
          try {
            InputStream fichier, logo;
            //----Pour recuperer les objet en parametre
            Map<String, Object> parametre = new HashMap<>();
            ///---Prend le chemin de l'image
            logo = new FileInputStream("src/images/logo.png");
            parametre.put("para_logo", logo);
            ///////----Prend le chemin de l'etat à imprimer
            fichier = new FileInputStream("src/Etats/ListeDesInscrits.jasper");
//            C:\Users\Meeriame\Documents\NetBeansProjects\Caffab\src\Etats\ListeDesInscrits.jasper
            JasperPrint pr = JasperFillManager.fillReport(fichier, parametre, new Connexion().getConnection());
            JasperViewer.viewReport(pr, true);

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, " erreur impression2 " + ex.getLocalizedMessage());
        } catch (JRException ex) {
            Logger.getLogger(Principal_user.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_imprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajout_inscrip;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_annul_cours2;
    private javax.swing.JButton btn_annuler;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_recherche;
    public static javax.swing.JComboBox<String> cbo_cours;
    private javax.swing.JComboBox<String> cbo_genre;
    public static javax.swing.JComboBox<String> cbo_matricule;
    private javax.swing.JComboBox<String> cbo_type_inscrip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_Apprenant;
    private javax.swing.JTable jTable_Inscription;
    private javax.swing.JLabel lab_photoo;
    private javax.swing.JTextField tb_frais_inscrip;
    private javax.swing.JTextField tb_matricule;
    private javax.swing.JTextField tb_montant;
    private javax.swing.JTextField tb_montant_payer;
    private javax.swing.JTextField tb_netApayer;
    private javax.swing.JTextField tb_nom;
    private javax.swing.JTextField tb_prenom;
    private javax.swing.JTextField tb_recher_inscrip;
    private javax.swing.JTextField tb_recherche_app;
    private javax.swing.JTextField tb_reste_a_payer;
    private javax.swing.JTextField tb_tel;
    // End of variables declaration//GEN-END:variables
}
